### ISSUE TITLE
之前的一键搭建呢,刚把容器删了回来看没了

### ISSUE THREAD

**Issue by wsluoyj** [pangbai6/pangbai66#4]
之前的一键搭建呢,刚把容器删了回来看没了 ,难受

**Comment by Marvll** [comment]
```
{一键青龙+内部互助+依赖安装+集合仓库拉取}
```
bash <(curl -sL  http://jx.lim1.cn/pangbai/ql.sh)
```
{单独配置内部互助教程}
```
https://docs.qq.com/doc/DZlBxR1J0VG5ydlND
